USE pruebas_practicas;
INSERT INTO TEST_CLIENTES VALUES (NULL, 'RUBEN DIAZ', 'C/ DEL ARCOIRIS, 69', 'VAYA PRUEBECITA','666999666','P');
INSERT INTO TEST_CLIENTES VALUES (NULL, 'ANTONIO MENDEZ', 'C/ DE LA PIRULETA, 69', 'VAYA PRUEBECITA2','666777666','N');
INSERT INTO TEST_CLIENTES VALUES (NULL, 'MANUEL SALGUERO', 'C/ DEL TRAFICO, 69', 'VAYA PRUEBECITA3','696969696','P');